# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gvVhnJlztjn8hzaSNB-OX8tIhb1p9MM7
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit

import streamlit as st
import numpy as np
import pickle

# --- Load the saved model and scaler ---
# The code assumes you have saved 'kmeans_model.pkl' and 'scaler.pkl'
with open('kmeans_model.pkl', 'rb') as f:
    kmeans_model = pickle.load(f)

with open('scaler.pkl', 'rb') as f:
    scaler = pickle.load(f)

cluster_descriptions = {
    0: "High-Spending Restaurants & Hotels",
    1: "Small Grocery Stores",
    2: "Large Supermarkets / Major Retailers",
    3: "Low-Spending / Occasional Customers",
    4: "Average-Spending Customers",
    5: "Small Convenience Stores",
}



# --- Set up the Streamlit app interface ---
st.title('Wholesale Customer Clustering App')
st.write('Enter the spending data for a new customer to predict their cluster.')

# --- Create input fields for each feature ---
fresh = st.number_input('Fresh Spending', min_value=0, value=10000)
milk = st.number_input('Milk Spending', min_value=0, value=5000)
grocery = st.number_input('Grocery Spending', min_value=0, value=8000)
frozen = st.number_input('Frozen Spending', min_value=0, value=2000)
detergents_paper = st.number_input('Detergents & Paper Spending', min_value=0, value=1000)
delicassen = st.number_input('Delicassen Spending', min_value=0, value=500)

# --- Add a button to make a prediction ---
if st.button('Predict Cluster'):
    # Create the new data point
    new_data = np.array([[fresh, milk, grocery, frozen, detergents_paper, delicassen]])

    # Apply log transformation and then scaling
    new_data_log = np.log(new_data)
    new_data_scaled = scaler.transform(new_data_log)

    # Predict the cluster using the loaded model
    predicted_cluster_id = kmeans_model.predict(new_data_scaled)[0]

    # Get the description from our dictionary
    cluster_description = cluster_descriptions.get(predicted_cluster_id, "Unknown Cluster")

    # Display the result
    st.success(f'The new customer belongs to Cluster: {predicted_cluster_id} - {cluster_description}')

# !pip install pyngrok

# from pyngrok import ngrok
# import time

# # Add your authentication token here
# # We need to set the auth token every time we run the session
# ngrok.set_auth_token("31LCepLlI6r0z9ijP3fSOxXSSIY_4t2nmvuoPDmLxmVtZDQvq")
# # First, kill any existing ngrok tunnels
# ngrok.kill()
# # Wait for a couple of seconds to ensure the process is terminated
# time.sleep(2)

# # Now, run the Streamlit app in the background
# !streamlit run app.py &>/dev/null&

# # Create a new public URL
# public_url = ngrok.connect(addr='8501')
# print("Streamlit Public URL:", public_url)

